kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'hello-app', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'hello-app')
        }
